добавила функцию для проверки валидности email-адреса validateEmail и тесты
sashalesotho/Twitter-demo pull request #13
Opened 2024-09-08 20:25 UTC by sashalesotho

2024-09-09 23:19 UTC, burtovoy requested changes

2024-09-09 23:19 UTC, burtovoy commented on tests/is_valid_email.test.js
> +		const expectedResult = true;
давай отступ в 2 пробела использовать

2024-09-09 23:19 UTC, burtovoy commented on .eslintrc.json
> +	  "indent": 0,
зачем это отключено?

2024-09-10 06:24 UTC, sashalesotho commented on .eslintrc.json
> +	  "indent": 0,
потому что я пользуюсь табами и забыла как использовать --fix
теперь вспомнила!

2024-09-10 06:25 UTC, sashalesotho commented on tests/is_valid_email.test.js
> +		const expectedResult = true;
ok

2024-09-13 00:50 UTC, merged